# Generated by Django 6.0.3 on 2026-03-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('issue_type', models.CharField(choices=[('power_outage', 'Power Outage'), ('loadshedding', 'Loadshedding'), ('cable_theft', 'Cable Theft'), ('damaged_cable', 'Damaged Cable'), ('transformer', 'Transformer Fault'), ('meter', 'Faulty Meter'), ('trip_switch', 'Main Switch Tripping'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('area_name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('assigned', 'Assigned'), ('repairing', 'Repairing'), ('resolved', 'Resolved')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
