# Generated by Django 6.0.3 on 2026-03-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_issuereport_assigned_to_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('awaiting_materials', 'Awaiting Materials'), ('resolved', 'Resolved'), ('incomplete', 'Incomplete')], default='received', max_length=20),
        ),
    ]
